name: GitHub Pages로 웹 OMR 배포

on:
  push:
    branches: [main]

  # Actions 탭에서 수동으로 워크플로 실행 허용
  workflow_dispatch:

# GitHub Pages로 배포할 수 있도록 GITHUB_TOKEN의 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 진행 중인 배포와 마지막으로 들어온 배포 사이의 실행을 건너뛰고, 한번에 한 가지 배포만 허용
# 진행 중인 실행을 취소하지는 않음
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Node 셋업
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Pages 셋업
        id: pages
        uses: actions/configure-pages@v5

      - name: 의존성 설치
        run: pnpm i --frozen-lockfile

      - name: 빌드
        run: pnpm build

      - name: 빌드 결과물 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 3

    steps:
      - name: GitHub Pages로 배포
        id: deployment
        uses: actions/deploy-pages@v4
